### ISSUE TITLE
Notebookserver not secure

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#148]
When I now want to access the notebook server I actually get the following unsafe certificate warning:

![Screenshot from 2020-03-13 11-44-37](https://user-images.githubusercontent.com/3668316/76619323-7be32a80-6522-11ea-8105-7f9bfc24f8ba.png)

**Comment by chryswoods** [comment]
Yes - the issue is that letsencrypt have migrated to a new protocol that is not supported by jupyterhub yet. We’re having to wait, and will then need to upgrade everything. Until then it is http only...

**Comment by jmichel80** [comment]
Any update on this?

**Comment by chryswoods** [comment]
Only update is that there is no update. It’s a pre-Covid job that has been delayed while we’ve been focusing on everything else. Things are beginning to calm down now so will likely look at this later in the month or in August.

It does still work over http, and as no sensitive data is exchanged it is not too bad (although I would much prefer to get a certificate sorted).

It is a half-day job though, as upgrading jupyterhub on top of the conda used for BioSimSpace normally throws up lots of conda issues, and then exposes lots of edge case jupyterhub bugs. It’s not a simple job...

**Comment by lohedges** [comment]
Seems to be working now so I'll close.

**Comment by chryswoods** [comment]
I don't think this is fixed. I still get the same error and see a fake kubernetes ingress certificate. It may be that we need to wait for the certificate to propagate, but it may be worth checking if the config has letsencrypt set up (or if the logs show any errors getting the certificate)

**Comment by lohedges** [comment]
Oh, strange. I don't get that on Firefox on Linux. I've cleared everything and even tried in a private tab. That said, the connection isn't marked as secure in the address bar.

I'll investigate further.

**Comment by lohedges** [comment]
Okay, I'm seeing this in the logs:

```
time="2020-09-29T19:44:49Z" level=info msg="requesting certificate for notebook.biosimspace.org" context=ingress_tls name=jupyterhub-internal namespace=notebook
time="2020-09-29T19:44:51Z" level=error msg="Error while processing certificate requests: 403 urn:acme:error:unauthorized: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details." context=kubelego
```

This is from using:

```
kubectl --namespace notebook logs autohttps-85cf4d9f89-jvhcs kube-lego | grep -i cert 
```

[This](https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430) is the link to the page in the error message. Will try to figure out how to solve this.

**Comment by chryswoods** [comment]
Yes, that’s the error message that shows that jupyter is using the old lego module that isn’t compatible with letsencrypt any more. Last time I looked (a while back) there was talk on the JupyterHub issues on how they would fix this. I don’t know if they have made any progress.

**Comment by chryswoods** [comment]
Here’s the link to the issue. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1448

**Comment by chryswoods** [comment]
Indeed, I see both Chris and Gareth have referred to the pull request in that issue for their JupyterHub installations (Isambard and HUGs) so should be able to let you know how they fixed things...

**Comment by lohedges** [comment]
Brilliant, thanks for the info. I'll take a look after lunch. At least I now understand why it was working intermittently.

**Comment by lohedges** [comment]
The supposed solution is to upgrade to JupyterHub 0.9.0, following the instructions [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/CHANGELOG.md#090---2020-04-15).

I've done this and restarted the hub but now see the following error when running:

```
kubectl --namespace notebook logs autohttps-5cc59f98f6-nm8zm traefik
```

(traefik has replaced nginx and kube-lego.)

```
time="2020-09-30T12:53:26Z" level=error msg="Unable to obtain ACME certificate for domains \"notebook.biosimspace.org\" : unable to generate a certificate for the domains [notebook.biosimspace.org]: acme: Error -> One or more domains had a problem:\n[notebook.biosimspace.org] acme: error: 400 :: urn:ietf:params:acme:error:connection :: Fetching http://notebook.biosimspace.org/.well-known/acme-challenge/...: Connection reset by peer, url: \n" providerName=le.acme
```

(Note that part of web address above has been redacted.)

[notebook.biosimspace.org](https://notebook.biosimspace.org) is currently unreachable, as is the hub IP address.

Perhaps it's just a case of waiting?

**Comment by chryswoods** [comment]
Check the services to make sure that it is using the same IP address. It may be that the load balancer has changed and so it has requested a new dynamic IP address. We would then need to update the DNS so that notebook.biosimspace.org resolves to the correct place. You can view the IP address by querying the kubernetes loadbalancer service (if memory serves).

**Comment by chryswoods** [comment]
Also, I've just checked the Oracle console and we should upgrade kubernetes. Currently it is 1.15.7, but we should upgrade to 1.16.8. This is a simple task of autoscaling down to 0 nodes and then clicking "upgrade" on the Oracle console, and then autoscaling back up to N nodes once the upgrade is complete.

**Comment by chryswoods** [comment]
I've just logged onto k8s via the Oracle cloud shell and it seems that the IP address has been preserved. I've emailed you the output of "kubectl --namespace notebook get services"

**Comment by chryswoods** [comment]
I think, looking at the services, that the old kube-lego (and related)services are still running, and have the BioSimSpace IP. They were not shut down by the upgrade, despite the pods going. The proxy-http service (the only new one that is less than 200 days old) is the new one for the new certificate fetcher. But this doesn't have a public IP, so isn't reachable.

This may be best solved by a "turn it off and then on again" approach, particularly as kubernetes needs to be upgraded. It may be worth completely destroying the cluster and then creating a new one. Installing BioSimSpace into that, and once we have the IP address of the new cluster, updating the DNS so that then letsencrypt can resolve and fetch the certificate.

**Comment by lohedges** [comment]
I tried the on/off approach earlier and that didn't seem to fix things. I'll try the upgrade and manually deleting the redundant services. After that comes the nuclear option...

**Comment by lohedges** [comment]
I rebuilt the Kubernetes cluster and everything is now working. Phew.
